language: "ruby"
cache: bundler

rvm:
  - "1.9"
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
  - "jruby-1.7"
  - "jruby-9.1"

sudo: false
gemfile:
  - gemfiles/Gemfile.ruby_19.x
  - gemfiles/Gemfile.multi_json.x
  - gemfiles/Gemfile.yajl-ruby.x
  - gemfiles/Gemfile.uuidtools.x
